# GitHub Actions - Android CI/CD
name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # 3. 设置Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # 4. 授权Gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 5. 构建Debug APK
      - name: Build debug APK with Gradle
        run: ./gradlew assembleDebug

      # 6. 上传APK作为构建产物
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
